version: 2.1

lein_image: &lein_image
  image: circleci/clojure-service:java11-0.10-dev
  auth:
    username: $DOCKER_HUB_USER
    password: $DOCKER_HUB_PASSWORD

jobs:
  test:
    docker:
      - *lein_image
    steps:
      - checkout
      - run:
          name: Ensure corpus tests are generated
          command: |
            lein generate-corpus
            if git diff --exit-code; then
              echo "Test corpus up to date"
            else
              echo "Regenerate corpus tests with 'lein generate-corpus' and check in the changes"
              exit 1
            fi
      - run: lein test
      - run: lein with-profile +cljfmt cljfmt check

  deploy-jar:
    docker:
      - *lein_image
    steps:
      - checkout
      - run:
          name: Compute version
          command: |
            set -o errexit
            set -o nounset
            version="1.0.<<pipeline.number>>-${CIRCLE_SHA1:0:7}"
            echo "export VERSION=\"${version}\"" >> ${CIRCLE_SHELL_ENV}
            echo $version
      - run: lein jar
      - run: lein with-profile +deploy deploy circle-s3

  test-go:
    docker:
      - image: cimg/go:1.25
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - run:
          command: task lint
          working_directory: go
      - run:
          command: task test
          working_directory: go

workflows:
  build-and-deploy:
    jobs:
      - test:
          context: org-global
      - test-go:
          context: org-global
      - deploy-jar:
          context:
            - org-global
            - circle-jars-publisher
          requires:
            - test
          filters:
            branches:
              only: main
