// Generates src/pipeline-values.generated.ts from the pipeline values registry shared
// with the Go and Clojure implementations.
//
// Usage: node scripts/generate-pipeline-values.ts

import { readFileSync, writeFileSync } from 'node:fs';
import { parse } from 'yaml';

const source = new URL(
  '../../domains/resources/com/circleci/expr/domains/pipeline-values.yml',
  import.meta.url,
);
const target = new URL('../src/pipeline-values.generated.ts', import.meta.url);

interface RawField {
  name: string;
  type?: string;
  domain?: string;
  defn?: string;
  private?: boolean;
  deprecation_at?: string;
  replaced_by?: string;
}

const { fields } = parse(readFileSync(source, 'utf8'), {
  // Keep dates as strings.
  schema: 'core',
}) as { fields: RawField[] };

const generated = fields.map((f) => ({
  name: f.name,
  type: f.type ?? 'string',
  ...(f.domain === undefined ? {} : { domain: f.domain }),
  ...(f.defn === undefined ? {} : { description: f.defn }),
  ...(f.private === true ? { private: true } : {}),
  ...(f.deprecation_at === undefined
    ? {}
    : { deprecatedAt: String(f.deprecation_at) }),
  ...(f.replaced_by === undefined ? {} : { replacedBy: f.replaced_by }),
}));

writeFileSync(
  target,
  `// Code generated by scripts/generate-pipeline-values.ts from
// domains/resources/com/circleci/expr/domains/pipeline-values.yml. DO NOT EDIT.

import type { PipelineValueField } from './pipeline-values.ts';

/** The pipeline value fields, from the authoritative registry. */
export const pipelineValueFields: readonly PipelineValueField[] = ${JSON.stringify(generated, null, 2)};
`,
);
