version: '3'

tasks:
  lint:
    desc: Lint code
    cmds:
      - go tool golangci-lint run

  test:
    desc: Run the tests
    cmds:
      - go tool gotestsum ./... -- -race

  fmt:
    desc: Fmt the code
    cmds:
      - gofmt -l -w -s .

  tidy:
    desc: Tidy up
    cmds:
      - go mod tidy
