version: '3'

tasks:
  lint:
    desc: Lint code
    cmds:
      - go tool -modfile=tools/go.mod golangci-lint run

  test:
    desc: Run the tests
    vars:
      ARGS: '{{default "./..." .CLI_ARGS}}'
    cmds:
      - go tool -modfile=tools/go.mod gotestsum -- -race {{.ARGS}}

  fmt:
    desc: Fmt the code
    cmds:
      - gofmt -l -w -s .

  tidy:
    desc: Tidy up
    cmds:
      - go mod tidy
      - go mod tidy -C tools
