// Code generated by scripts/generate-pipeline-values.ts from
// domains/resources/com/circleci/expr/domains/pipeline-values.yml. DO NOT EDIT.

import type { PipelineValueField } from './pipeline-values.ts';

/** The pipeline value fields, from the authoritative registry. */
export const pipelineValueFields: readonly PipelineValueField[] = [
  {
    name: 'pipeline.config.file_path',
    type: 'string',
    description:
      'The path to the CircleCI configuration file within the config repository, relative to the repo root.',
  },
  {
    name: 'pipeline.config.ref',
    type: 'string',
    description:
      'The full Git ref (e.g., refs/heads/main) used to fetch the configuration file from the config repository.',
  },
  {
    name: 'pipeline.config.repository.name',
    type: 'string',
    description:
      'The name of the config source repository, in the format owner/repo-name.',
  },
  {
    name: 'pipeline.config.repository.url',
    type: 'string',
    description: 'The VCS provider URL of the config source repository.',
  },
  {
    name: 'pipeline.config.file_type',
    type: 'string',
    description: 'The config file type, defaults to circleci.',
  },
  {
    name: 'pipeline.config.sha',
    type: 'string',
    description:
      'The Git SHA of the commit from which the configuration file was fetched.',
  },
  {
    name: 'pipeline.config_source',
    type: 'string',
    domain: 'providers',
    description: 'Specifies the provider of the pipeline build config.',
    private: true,
  },
  {
    name: 'pipeline.definition.id',
    type: 'uuid',
    domain: 'config-sources',
    description:
      'Identifies the definition of the pipeline, including its checkout and config sources.',
  },
  {
    name: 'pipeline.deploy.component_name',
    type: 'string',
    description:
      'The name of the deployable component targeted by this pipeline, injected by the deploy orchestration system.',
  },
  {
    name: 'pipeline.deploy.current_version',
    type: 'string',
    description:
      'The version string of the currently deployed component, injected by the deploy orchestration system.',
  },
  {
    name: 'pipeline.deploy.environment_name',
    type: 'string',
    description:
      'The name of the target deployment environment (e.g., production, staging), injected by the deploy orchestration system.',
  },
  {
    name: 'pipeline.deploy.namespace',
    type: 'string',
    description:
      'The deployment namespace within the target environment, injected by the deploy orchestration system.',
  },
  {
    name: 'pipeline.deploy.reason',
    type: 'string',
    description:
      'A string describing why the deployment or rollback was triggered, injected by the deploy orchestration system.',
  },
  {
    name: 'pipeline.deploy.target_version',
    type: 'string',
    description:
      'The version string of the component to be deployed or rolled back to, injected by the deploy orchestration system.',
  },
  {
    name: 'pipeline.event.action',
    type: 'string',
    description:
      'The specific action associated with the triggering event (e.g., opened, synchronize, closed for pull request events). For event types with no action subtype, this value is identical to pipeline.event.name.',
  },
  {
    name: 'pipeline.event.circleci_actor_id',
    type: 'uuid',
    domain: 'users',
    private: true,
  },
  {
    name: 'pipeline.event.context.github.pr_url',
    type: 'string',
    description:
      'The HTML URL of the associated pull request: for push events, the open PR whose head branch was pushed to; for pull request events, the PR that triggered the event.',
  },
  {
    name: 'pipeline.event.context.github.sha',
    type: 'string',
    domain: 'git-shas',
    description:
      'Identifies the commit to which the notification about the pipeline outcome will be sent.',
  },
  {
    name: 'pipeline.event.github.after',
    type: 'string',
    description:
      "The HEAD SHA of the branch after the push, from the GitHub push webhook payload's after field. Populated only for push events.",
  },
  {
    name: 'pipeline.event.github.comment.body',
    type: 'string',
    description:
      'The pull request comment body with leading/trailing whitespace removed, if a pipeline was triggered via PR comment. For pipelines triggered in other ways, this value is undefined.',
  },
  {
    name: 'pipeline.event.github.head_commit.url',
    type: 'string',
    description:
      'The URL of the HEAD commit from the push webhook payload. Populated only for push events.',
  },
  {
    name: 'pipeline.event.github.label.name',
    type: 'string',
    description:
      'The name of the label applied to the pull request, from the GitHub webhook payload. Only present for pull_request events whose "action" field value is "labeled".',
  },
  {
    name: 'pipeline.event.github.pull_request.base.ref',
    type: 'string',
    domain: 'git-branches',
    description:
      'The name of the base branch of the pull request, from the GitHub webhook payload.',
  },
  {
    name: 'pipeline.event.github.pull_request.base.sha',
    type: 'string',
    domain: 'git-shas',
    description:
      'The SHA of the HEAD of the base branch of the pull request, from the GitHub webhook payload.',
  },
  {
    name: 'pipeline.event.github.pull_request.draft',
    type: 'boolean',
    description:
      'Whether the pull request is in draft state, from the GitHub webhook payload.',
  },
  {
    name: 'pipeline.event.github.pull_request.head.ref',
    type: 'string',
    domain: 'git-branches',
    description:
      'The name of the head branch of the pull request, from the GitHub webhook payload.',
  },
  {
    name: 'pipeline.event.github.pull_request.head.sha',
    type: 'string',
    domain: 'git-shas',
    description:
      'The SHA of the HEAD of the head branch of the pull request, from the GitHub webhook payload.',
  },
  {
    name: 'pipeline.event.github.pull_request.merged',
    type: 'boolean',
    description:
      'Whether the pull request has been merged, from the GitHub webhook payload.',
  },
  {
    name: 'pipeline.event.github.pull_request.number',
    type: 'uint',
    description:
      'The numeric identifier of the pull request, from the GitHub webhook payload.',
  },
  {
    name: 'pipeline.event.github.pull_request.title',
    type: 'string',
    description:
      'The title of the pull request, from the GitHub webhook payload.',
  },
  {
    name: 'pipeline.event.github.pull_request.url',
    type: 'string',
    domain: 'urls',
    description:
      'The HTML URL of the pull request, from the GitHub webhook payload.',
  },
  {
    name: 'pipeline.event.github.ref',
    type: 'string',
    description:
      "The full Git ref (e.g., refs/heads/main, refs/tags/v1.0) from the GitHub push webhook payload's ref field. Populated only for push events.",
  },
  {
    name: 'pipeline.event.github.repository.name',
    type: 'string',
    description:
      "The repository name from the GitHub webhook payload's repository.name field.",
  },
  {
    name: 'pipeline.event.github.repository.owner.login',
    type: 'string',
    description:
      "The owner's GitHub login from the webhook payload's repository.owner.login field.",
  },
  {
    name: 'pipeline.event.github.repository.url',
    type: 'string',
    description:
      "The repository HTML URL from the GitHub webhook payload's repository.html_url field.",
  },
  {
    name: 'pipeline.event.github.sender.avatar_url',
    type: 'string',
    description:
      "The avatar URL of the GitHub user who sent the event, from the webhook payload's sender.avatar_url field.",
  },
  {
    name: 'pipeline.event.github.sender.login',
    type: 'string',
    description:
      "The GitHub login of the user who sent the event, from the webhook payload's sender.login field.",
  },
  {
    name: 'pipeline.event.github.sender.type',
    type: 'string',
    description:
      'The type of GitHub user that emitted the event triggering the pipeline. Possible values are User, Organization, and Bot.',
  },
  {
    name: 'pipeline.event.name',
    type: 'string',
    description:
      'Normalized event name string indicating the trigger event type (e.g., push, pull_request, api, schedule).',
  },
  {
    name: 'pipeline.event.provider_actor_id',
    type: 'string',
    description: "Identifies the provider's user that triggered the pipeline.",
    private: true,
  },
  {
    name: 'pipeline.event.provider_login',
    type: 'string',
  },
  {
    name: 'pipeline.git.base_revision',
    type: 'string',
  },
  {
    name: 'pipeline.git.branch',
    type: 'string',
    domain: 'git-branches',
    description:
      'Specifies the git branch from which to checkout the project source.',
  },
  {
    name: 'pipeline.git.branch.is_default',
    type: 'boolean',
    description:
      "Indicates that the git branch from which to checkout the project source is the repository's default branch.",
  },
  {
    name: 'pipeline.git.commit.author_avatar_url',
    type: 'string',
    domain: 'urls',
    description:
      'The url of the avatar of the author of the last commit in the checkout branch.',
    private: true,
  },
  {
    name: 'pipeline.git.commit.author_date',
    type: 'string',
  },
  {
    name: 'pipeline.git.commit.author_email',
    type: 'string',
    domain: 'emails',
    description:
      'The email address of the author of the last commit in the checkout branch.',
    private: true,
  },
  {
    name: 'pipeline.git.commit.author_login',
    type: 'string',
    description:
      'The login name, at the vcs provider, of the author of the last commit in the checkout branch.',
  },
  {
    name: 'pipeline.git.commit.author_name',
    type: 'string',
    description:
      'The name of the author of the last commit in the checkout branch.',
    private: true,
  },
  {
    name: 'pipeline.git.commit.body',
    type: 'string',
    description:
      'The body of the message in the last commit in the checkout branch.',
  },
  {
    name: 'pipeline.git.commit.committer_date',
    type: 'string',
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.git.commit.committer_email',
    type: 'string',
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.git.commit.committer_login',
    type: 'string',
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.git.commit.committer_name',
    type: 'string',
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.git.commit.subject',
    type: 'string',
    description:
      'The subject of the message in the last commit in the checkout branch.',
  },
  {
    name: 'pipeline.git.commit.url',
    type: 'string',
    domain: 'urls',
    description:
      'The vcs provider url of the last commit in the checkout branch.',
  },
  {
    name: 'pipeline.git.origin_repo_id',
    type: 'string',
  },
  {
    name: 'pipeline.git.origin_repo_url',
    type: 'string',
    domain: 'urls',
  },
  {
    name: 'pipeline.git.repo_id',
    type: 'string',
    description: "The vcs provider's identifier for the checkout repository.",
  },
  {
    name: 'pipeline.git.repo_name',
    type: 'string',
    domain: 'git-repo-names',
    description: 'The name of the checkout repository.',
  },
  {
    name: 'pipeline.git.repo_owner',
    type: 'string',
    description:
      "The vcs provider's name for the owner of the checkout repository.",
  },
  {
    name: 'pipeline.git.repo_url',
    type: 'string',
    domain: 'urls',
    description: 'The vcs provider url of the checkout repository.',
  },
  {
    name: 'pipeline.git.revision',
    type: 'string',
    domain: 'git-shas',
    description: 'The SHA of the last commit in the checkout branch.',
  },
  {
    name: 'pipeline.git.ssh_checkout_url',
    type: 'string',
    domain: 'git-urls',
    description: 'The git url of the repository hosted by the vcs provider.',
    private: true,
  },
  {
    name: 'pipeline.git.tag',
    type: 'string',
    domain: 'git-tags',
    description:
      'The name of the git tag being checked out. Not populated when checking out a branch.',
  },
  {
    name: 'pipeline.git.target_repo_url',
    type: 'string',
    domain: 'urls',
  },
  {
    name: 'pipeline.id',
    type: 'uuid',
    domain: 'pipelines',
    description: 'Identifies the triggered pipeline.',
  },
  {
    name: 'pipeline.integration_source',
    type: 'string',
    domain: 'providers',
    description:
      'The pipeline type determined by checkout provider (e.g., github_app, github, bitbucket, bitbucket_dc, gitlab). Used by workflows-conductor to gate SSH key requirements, by execution to determine checkout strategy, and by notifications to determine commit status update behaviour.',
  },
  {
    name: 'pipeline.name',
    type: 'string',
    description:
      'Human-readable name of the pipeline definition, as stored in the config source record in soc-integrations.',
  },
  {
    name: 'pipeline.number',
    type: 'uint',
    description:
      'Monotonically incrementing integer scoped to the project, assigned by builds-service at pipeline creation.',
  },
  {
    name: 'pipeline.parameters.*',
    type: 'string',
    description:
      'The set of customer parameters that characterizes the pipeline. Multiple such entries can be present, with the wildcard being a non-empty string and the value a string, number, or boolean.',
  },
  {
    name: 'pipeline.project.git_url',
    type: 'string',
    domain: 'urls',
    deprecatedAt: '2027-01-01',
  },
  {
    name: 'pipeline.project.slug',
    type: 'string',
    domain: 'project-slugs',
    description:
      'The unique slug for the project for which the pipeline is being run.',
  },
  {
    name: 'pipeline.project.type',
    type: 'string',
    domain: 'providers',
    description:
      'The type of the organization owning the project; one of github, circleci, or bitbucket.',
  },
  {
    name: 'pipeline.project.url',
    type: 'string',
    domain: 'urls',
    description:
      'The CircleCI URL of the project for which the pipeline is being run.',
    private: true,
  },
  {
    name: 'pipeline.schedule.id',
    type: 'uuid',
    description:
      'UUID of the schedule record that triggered the pipeline. Populated only for schedule-triggered pipelines.',
  },
  {
    name: 'pipeline.schedule.name',
    type: 'string',
    description:
      'Human-readable name of the schedule that triggered the pipeline. Populated only for schedule-triggered pipelines.',
    deprecatedAt: '2027-01-01',
    replacedBy: 'pipeline.trigger.name',
  },
  {
    name: 'pipeline.trigger.id',
    type: 'uuid',
    domain: 'triggers',
    description: 'Identifies the trigger that initiated the pipeline.',
  },
  {
    name: 'pipeline.trigger.name',
    type: 'string',
    description: 'Names the trigger that initiated the pipeline.',
    private: true,
  },
  {
    name: 'pipeline.trigger.received_at',
    type: 'timestamp',
    description:
      'The moment at which the event which triggered the pipeline was received.',
  },
  {
    name: 'pipeline.trigger.type',
    type: 'string',
    domain: 'providers',
    description:
      'Specifies the type of trigger that initiated the pipeline; one of github_app, github, bitbucket_dc, schedule, or webhook.',
  },
  {
    name: 'pipeline.trigger_parameters.circleci.actor_id',
    type: 'uuid',
    private: true,
    deprecatedAt: '2027-01-01',
  },
  {
    name: 'pipeline.trigger_parameters.circleci.config_source_id',
    type: 'string',
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.circleci.event_action',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.circleci.event_time',
    type: 'string',
    deprecatedAt: '2026-08-01',
    replacedBy: 'pipeline.trigger.received_at',
  },
  {
    name: 'pipeline.trigger_parameters.circleci.event_type',
    type: 'string',
    deprecatedAt: '2026-08-01',
    replacedBy: 'pipeline.event.name',
  },
  {
    name: 'pipeline.trigger_parameters.circleci.provider_actor_id',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.circleci.provider_login',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.circleci.provider_name',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.circleci.trigger_id',
    type: 'string',
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.circleci.trigger_type',
    type: 'string',
    deprecatedAt: '2026-08-01',
    replacedBy: 'pipeline.trigger.type',
  },
  {
    name: 'pipeline.trigger_parameters.event.description',
    type: 'string',
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.event.title',
    type: 'string',
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.git.author_avatar_url',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.git.author_login',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.git.branch',
    type: 'string',
    private: true,
    deprecatedAt: '2027-01-01',
  },
  {
    name: 'pipeline.trigger_parameters.git.checkout_sha',
    type: 'string',
    private: true,
    deprecatedAt: '2027-01-01',
  },
  {
    name: 'pipeline.trigger_parameters.git.checkout_url',
    type: 'string',
    private: true,
    deprecatedAt: '2027-01-01',
  },
  {
    name: 'pipeline.trigger_parameters.git.commit_author_email',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.git.commit_author_name',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.git.commit_message',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.git.default_branch',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.git.ref',
    type: 'string',
    private: true,
    deprecatedAt: '2027-01-01',
  },
  {
    name: 'pipeline.trigger_parameters.git.repo_name',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.git.repo_owner',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.git.repo_url',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.git.tag',
    type: 'string',
    private: true,
    deprecatedAt: '2027-01-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.action',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.branch',
    type: 'string',
    deprecatedAt: '2026-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.checkout_sha',
    type: 'string',
    deprecatedAt: '2026-08-01',
    replacedBy: 'pipeline.git.revision',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.commit_author_email',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.commit_author_name',
    type: 'string',
    deprecatedAt: '2026-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.commit_message',
    type: 'string',
    deprecatedAt: '2026-08-01',
    replacedBy: 'pipeline.git.commit.body',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.commit_sha',
    type: 'string',
    deprecatedAt: '2026-08-01',
    replacedBy: 'pipeline.event.github.after',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.commit_timestamp',
    type: 'string',
    deprecatedAt: '2026-08-01',
    replacedBy: 'pipeline.trigger.received_at',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.commit_title',
    type: 'string',
    deprecatedAt: '2026-08-01',
    replacedBy: 'pipeline.git.commit.subject',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.default_branch',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.forced',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.full_ref',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.label_name',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.owner',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.pull_request_draft',
    type: 'string',
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.pull_request_head_sha',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.pull_request_merged',
    type: 'string',
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.ref',
    type: 'string',
    deprecatedAt: '2026-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.repo_full_name',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.repo_id',
    type: 'string',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.repo_name',
    type: 'string',
    deprecatedAt: '2026-08-01',
    replacedBy: 'pipeline.event.github.repository.name',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.repo_url',
    type: 'string',
    deprecatedAt: '2026-08-01',
    replacedBy: 'pipeline.event.github.repository.url',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.tag',
    type: 'string',
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.user_avatar',
    type: 'string',
    deprecatedAt: '2026-08-01',
    replacedBy: 'pipeline.event.github.sender.avatar_url',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.user_id',
    type: 'string',
    deprecatedAt: '2026-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.user_name',
    type: 'string',
    deprecatedAt: '2026-08-01',
    replacedBy: 'pipeline.event.github.sender.login',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.user_username',
    type: 'string',
    deprecatedAt: '2026-08-01',
    replacedBy: 'pipeline.event.github.sender.login',
  },
  {
    name: 'pipeline.trigger_parameters.github_app.web_url',
    type: 'string',
    deprecatedAt: '2026-08-01',
    replacedBy: 'pipeline.event.github.repository.url',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.action',
    type: 'string',
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.branch',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.checkout_sha',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.commit_author_email',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.commit_author_name',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.commit_message',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.commit_sha',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.commit_timestamp',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.commit_title',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.default_branch',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.is_fork_merge_request',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.project_id',
    type: 'string',
    private: true,
    deprecatedAt: '2027-01-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.ref',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.repo_name',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.repo_url',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.tag',
    type: 'string',
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.type',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.user_id',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.user_name',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.user_avatar',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.user_username',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.web_url',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.gitlab.x_gitlab_event_id',
    type: 'string',
    deprecatedAt: '2027-08-01',
  },
  {
    name: 'pipeline.trigger_parameters.webhook.body',
    type: 'string',
    description:
      'The request body of the custom webhook that triggered the pipeline run. This will be truncated if exceeds the maximum pipeline value length.',
  },
  {
    name: 'pipeline.trigger_source',
    type: 'string',
    domain: 'trigger-sources',
    description:
      'The trigger source category indicating how the pipeline was initiated; one of webhook, api, scheduled_pipeline, or schedule (the last being specific to schedule workflows).',
    deprecatedAt: '2026-08-01',
    replacedBy: 'pipeline.trigger.type',
  },
  {
    name: 'pipeline.vcs.event_type',
    type: 'string',
    private: true,
    deprecatedAt: '2026-08-02',
  },
  {
    name: 'pipeline.vcs.origin_repository_id',
    type: 'string',
    private: true,
    deprecatedAt: '2026-08-02',
  },
  {
    name: 'pipeline.vcs.origin_repository_url',
    type: 'string',
    domain: 'urls',
    private: true,
    deprecatedAt: '2026-08-02',
  },
  {
    name: 'pipeline.vcs.repository_url',
    type: 'string',
    domain: 'urls',
    description: 'The vcs provider url of the checkout source.',
    private: true,
    deprecatedAt: '2026-08-02',
  },
  {
    name: 'pipeline.vcs.revision',
    type: 'string',
    domain: 'git-shas',
    private: true,
    deprecatedAt: '2026-08-02',
  },
  {
    name: 'pipeline.vcs.target_repository_id',
    type: 'string',
    private: true,
    deprecatedAt: '2026-08-02',
  },
  {
    name: 'pipeline.vcs.target_repository_url',
    type: 'string',
    domain: 'urls',
    private: true,
    deprecatedAt: '2026-09-01',
  },
  {
    name: 'pipeline.vcs.type',
    type: 'string',
    domain: 'providers',
    private: true,
    deprecatedAt: '2026-08-02',
  },
];
